--- # Web playbook
- hosts: apacheweb
  user: test
  become: yes
  connection: ssh

  vars_files:
    - variables/variables.yml
  tasks:
    - include: packages/packages.yml
    - include: commands/commands.yml
  handlers:
    - include: handlers/handlers.yml

